import BlogHeader from '@/components/Header/BlogHeader'
import { sanityClient, urlFor } from '@/sanity'
import { Post } from '@/typings'
import { groq } from 'next-sanity'
import Head from 'next/head'
import Link from 'next/link'
import React from 'react'
import {motion} from "framer-motion"

interface Props {
  posts: [Post];
}

const index = ( { posts } : Props ) => {

  return (
    <div 
      className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory 
      shrink-0 overflow-y-scroll z-0 overflow-x-hidden scrollbar 
      scrollbar-track-gray-400/20 scrollbar-thumb-[#1ef70a]/80 '>
      <Head>
        <title>Mishkat Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BlogHeader/>
      <div className='flex items-center justify-center py-10 bg-green-600 border-y-black'>
        <motion.div 
        initial={{
          y:-300,
          opacity: 0,
          scale:0.5
        }}
        animate={{
          y:0,
          opacity:1,
          scale:1
        }}
        transition={{
          duration:1.5,
        }}
        className='items-center justify-center px-10 space-y-5 '>
          <h1 className='max-w-6xl font-serif text-lg md:text-3xl xl:text-6xl '>
            <span className='underline decoration-[#1ef70a]/80 decoration-4'>Mishkat Blogs</span>
              | My Blogs about my overall and individual experience and what i worked on.
            </h1>
          <h2 className='text-left md:text-center'>You can click on each of the cards to view all of the tech that i worked on.</h2>
        </motion.div>
      </div>

      <motion.div 
      initial={{
        x:-300,
        opacity: 0,
        scale:0.5
      }}
      animate={{
        x:0,
        opacity:1,
        scale:1
      }}
      transition={{
        duration:1.5,
      }}
      className='grid grid-cols-1 gap-3 p-2 mx-auto max-w-7xl sm:grid-cols-2 md:grid-cols-3 md:gap-6 md:p-6'>
        {posts.map(post=>(
          <Link key={post._id} href={`/blogs/${post.slug.current}`}>
            <div className='p-3 border rounded-lg cursor-pointer group border-neutral-500'>
              <img 
              src={urlFor(post.mainImage).url()} 
              className="object-cover w-full transition-transform duration-200 ease-in-out h-60 group-hover:scale-105"
              />
              <div className='flex justify-between mt-3 space-y-1'>
                <div className=''>
                  <p>{post.title}</p>
                  <p>{post.description.slice(0,45)}... by {post.author.name}</p>
                </div>
                <img src={urlFor(post.author.image).url()}
                className="w-12 h-12 rounded-full"/>
              </div>
            </div>
          </Link>
        ))}
      </motion.div>

    </div>
  )
}

export default index

export const getServerSideProps = async () => {
  const query = groq`*[ _type == "post" ]{
    _id,
    _createdAt,
    title,
    author->{
      name,
      image
    },
    description,
    mainImage,
    slug,
    title
  }`;


  const posts= await sanityClient.fetch(query);
  return{
    props:{
      posts
    }
  }

}

{/* <div className='grid max-w-6xl grid-cols-4 space-x-5'>
{posts.map(post=>(
  <Link key={post._id} href={`/blog/${post.slug.current}`}>
      <div className="max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
        <img className="rounded-t-lg" src={urlFor(post.mainImage).url()} alt="" />
        <div className="p-5">
          <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
            {post.title}
          </h5>
          <p className="mb-3 font-normal text-gray-700 dark:text-gray-400">test</p>
          <p  className="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
              Read more
              <svg aria-hidden="true" className="w-4 h-4 ml-2 -mr-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
          </p>
        </div>
      </div>
  </Link>
))}
</div> */}

{/* <nav className="w-full rounded-md">
  <ol className="flex list-reset">
    <li>
      <a
        href="#"
        className="transition duration-150 ease-in-out text-primary hover:text-primary-600 focus:text-primary-600 active:text-primary-700 dark:text-primary-400 dark:hover:text-primary-500 dark:focus:text-primary-500 dark:active:text-primary-600"
        >Home</a
      >
    </li>
    <li>
      <span className="mx-2 text-neutral-500 dark:text-neutral-400">/</span>
    </li>
    <li>
      <a
        href="#"
        className="transition duration-150 ease-in-out text-primary hover:text-primary-600 focus:text-primary-600 active:text-primary-700 dark:text-primary-400 dark:hover:text-primary-500 dark:focus:text-primary-500 dark:active:text-primary-600"
        >Library</a
      >
    </li>
    <li>
      <span className="mx-2 text-neutral-500 dark:text-neutral-400">/</span>
    </li>
    <li className="text-neutral-500 dark:text-neutral-400">Data</li>
  </ol>
</nav> */}